### ISSUE TITLE
Translation of new parameters

### ISSUE THREAD

**Issue by ParmuzinAlexander** [kaorahi/lizzie#1]
I can't find new parameters for translation:
Edit comment
Copy comment
Score game
Rule
Help-Keyboard controls

**Comment by kaorahi** [comment]
Have you noticed [LizzieYzy](https://github.com/yzyray/lizzieyzy/)? You may prefer it to the original Lizzie now.

...Or, do you still have any reason to keep the maintenance of Lizzie?

**Comment by ParmuzinAlexander** [comment]
Lizzie is simple and has everything I need. LizzieYzy like a monster and to be honest looks not safe. Too many things, but it's not necessary. Ok 6 lines it is not big problem.

**Comment by kaorahi** [comment]
This may fix your `NoRefreshDisplayedVariation` issue.

~~~
--- a/src/main/java/featurecat/lizzie/gui/ConfigDialog.java
+++ b/src/main/java/featurecat/lizzie/gui/ConfigDialog.java
@@ -1100,7 +1100,7 @@ public class ConfigDialog extends LizzieDialog {
 
     JLabel lblNotRefreshVaritions =
         new JLabel(resourceBundle.getString("LizzieConfig.title.notRefreshVariation"));
-    lblNotRefreshVaritions.setBounds(372, 308, 187, 16);
+    lblNotRefreshVaritions.setBounds(372, 308, 157, 16);
     uiTab.add(lblNotRefreshVaritions);
     chkNotRefreshVariation = new JCheckBox("");
     chkNotRefreshVariation.setBounds(536, 305, 57, 23);
~~~

**Comment by ParmuzinAlexander** [comment]
@kaorahi I just made it shorter, it's fine. =)

**Comment by kaorahi** [comment]
@ParmuzinAlexander, I added the following lines to `DisplayStrings.properties`.

~~~
Menu.game.editComment=Edit comment
Menu.game.copyComment=Copy comment(Ctrl+Shift+C)
Menu.game.scoreGame=Score game
Menu.analyze.rule=Rule
Menu.helpMenu=Help
Menu.helpMenu.keyboardControls=Keyboard controls
~~~

**Comment by kaorahi** [comment]
I overlooked 6f4d067f in featurecat#906 for a week...

Here is a binary with your updated RU translations. Enjoy!

https://github.com/kaorahi/lizzie/releases/tag/patched074_211211a

**Comment by ParmuzinAlexander** [comment]
Great. Thank you for support Lizzie.
