### ISSUE TITLE
Displaying move numbers on captured stones

### ISSUE THREAD

**Issue by hope366** [kaorahi/lizzie#10]
Thank you very much for fixing the bug in the markup tool last time.
This time as well as last time, this is a request regarding LizzieYzy.

Please see the figure below. 4-5 and 5-5 had "White 2" and "White 4".
It is not inconvenient at all when checking on the GUI, but it is a little troublesome to arrange the stones on the actual Go board while looking at this diagram.

Game records published in magazines and newspapers also display stones that have already been taken and are no longer on the board.

For people who use a real Go board to check their game records, could you please add an option to display stones that have already been taken and are no longer on the board?

![無題](https://github.com/kaorahi/lizzie/assets/63999713/d59f12ab-094e-4491-b848-27d5fcd8fcfc)

**Comment by kaorahi** [comment]
It's OK to make such requests, as long as you understand they are not my top priority. ;-)

Even when I have time and energy for hobby programming, I prefer to focus on my main projects. Right now, I have an original idea that I'm looking forward to implementing during holidays, if possible. So, I'd like to add this issue to my list of potential topics for casual programming when I'm in the mood for it. Please be aware that there's a large chance I might never actually work on this.

By the way, do you have any ideas on how to visualize move numbers of new stones being placed in captured positions? In lizgoban, I'm trying to show all the move numbers like "24,67" on such stones with small font. But this approach can make the numbers too small to read during long ko fights. So I'm also considering omitting earlier numbers in sequences like "25,28,31,34" and just showing the last few, for instance, as ",31,34".

**Comment by hope366** [comment]
＞It's OK to make such requests, as long as you understand they are not my top priority. ;-)

Normally, this would be a somewhat brazen request, so I am very grateful that you think of it that way.

Now, regarding the idea of how to display it, I'm worried that displaying many small numbers on one stone might make it hard to see.
I have never played a game record, but when I looked at the game records in a certain magazine, I found that the numbers that could not be displayed on the Go board were "❸(1), ④(2), ❺(1), ⑥(2)". )” (the specific numbers have no meaning)

Currently, when I print out a game record and show it to someone else, I attach a handwritten explanation like this, but I would appreciate it if you could prepare a description like this with one touch to save me the trouble. is.

**Comment by kaorahi** [comment]
To create complete diagrams in a printing style, it might be more fitting to use other SGF tools specifically designed for such tasks. In my view, the current issue seems to somewhat diverge from the original purpose of lizzie. For example, [Drago](https://github.com/GillesArcas/Drago) can convert [SGF to PDF](http://www.godrago.net/PrintSamples.html)? I've not tested it actually.

**Comment by hope366** [comment]
Looks like I posted my reply in the wrong place😅
Anyway, thank you very much for introducing me to "Drago".
