### ISSUE TITLE
when use auto analysis，this problem occurs。

### ISSUE THREAD

**Issue by some2112** [kaorahi/lizzie#3]
![image](https://user-images.githubusercontent.com/105207554/167386938-8f939702-a49f-4c5b-b665-1bfa6362e5c3.png)

**Comment by some2112** [comment]
But this problem does not appear in the official version

**Comment by kaorahi** [comment]
Thx for the report. Would you try this?

https://github.com/kaorahi/lizzie/releases/tag/patched074_test_kaorahi3a

**Comment by some2112** [comment]
solved thanks
