### ISSUE TITLE
can be marked?

### ISSUE THREAD

**Issue by some2112** [kaorahi/lizzie#4]
![image](https://user-images.githubusercontent.com/105207554/172397575-417c1907-79a9-476c-bf96-040de5fe6918.png)
If we mark it in sabaki in advance, we can still see the mark when the interface is opened.

Want to ask if we can mark it directly in the interface?
![image](https://user-images.githubusercontent.com/105207554/172398022-cbc1eb53-18fe-4b6a-bc27-fa143fa1f923.png)

**Comment by kaorahi** [comment]
This repository is unofficial. Please ask in the [official repository](https://github.com/featurecat/lizzie) or [LizzieYzy](https://github.com/yzyray/lizzieyzy). (The former seems inactive, though.)
