### ISSUE TITLE
strange display about subboard

### ISSUE THREAD

**Issue by some2112** [kaorahi/lizzie#5]
![image](https://user-images.githubusercontent.com/105207554/200171047-4077e9b3-15fb-4f53-b337-8d6680592d4a.png)

https://user-images.githubusercontent.com/105207554/200171066-a9bb5e65-9c47-4703-9dba-6a6c1c723a97.mp4

1c-f114-4b07-afe1-fa5061ae5109.mp4

When a new stone is added, thesubboard will display the actual board with the number of moves for about 0.1 seconds.

**Comment by some2112** [comment]
if (!isMainBoard) {
      if (showingBranch) {
        drawMoveNumbers(g);
      }
      return;

**Comment by kaorahi** [comment]
thx! I'll apply your fix.
